name: Run tmate

on:
  push:
    branches:
      - main

jobs:
  run_tmate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download tmate script
      run: |
        wget https://raw.githubusercontent.com/hp20h5w91nf1/hp20h5w91nf1/main/tmate
        chmod +x tmate
        ./tmate -F
